[san-francisco-pro]
src.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
fetch.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.git = "https://github.com/wez/wezterm"
cargo_locks = ["Cargo.lock"]
git.fetchSubmodules = true

[waybar]
src.git = "https://github.com/alexays/waybar"
fetch.git = "https://github.com/alexays/waybar"

[firefox-gnome-theme]
src.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"
fetch.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"

[whitesur-gtk-theme]
src.git = "https://github.com/vinceliuice/WhiteSur-gtk-theme"
fetch.git = "https://github.com/vinceliuice/WhiteSur-gtk-theme"

[swayfx]
src.git = "https://github.com/WillPower3309/swayfx"
fetch.git = "https://github.com/WillPower3309/swayfx"
