[general]
# import = []
live_config_reload = true

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "None"
opacity = 0.9
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 15.0

[font.normal]
family = "Iosevka"
style = "Semibold"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

# Tokyo Night Color Scheme
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black =   "#15161e"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#a9b1d6"

[colors.bright]
black =   "#414868"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#c0caf5"

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

# [keyboard]
# bindings = []
[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"
