[san-francisco-pro]
src.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
fetch.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"

[firefox-gnome-theme]
src.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"
fetch.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"

[whitesur-gtk-theme]
src.git = "https://github.com/vinceliuice/WhiteSur-gtk-theme"
fetch.git = "https://github.com/vinceliuice/WhiteSur-gtk-theme"

[catppuccin-fcitx5]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.git = "https://github.com/catppuccin/fcitx5"

[firefox-ui-fix]
src.git = "https://github.com/black7375/Firefox-UI-Fix"
fetch.git = "https://github.com/black7375/Firefox-UI-Fix"

[fuzzmoji]
src.git = "https://codeberg.org/codingotaku/fuzzmoji"
fetch.git = "https://codeberg.org/codingotaku/fuzzmoji"
